# Generated by Django 3.0.7 on 2020-09-06 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_auto_20200905_1009'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='postcade',
            new_name='postcode',
        ),
        migrations.AddField(
            model_name='order',
            name='county',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='country',
            field=models.CharField(max_length=40),
        ),
    ]
