# Generated by Django 3.0.7 on 2020-09-14 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_auto_20200905_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_cost',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='grand_total',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_total',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='postcode',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderlineitem',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
