# Generated by Django 3.0.7 on 2020-09-25 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0006_auto_20200923_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_cost',
            field=models.IntegerField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='grand_total',
            field=models.IntegerField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_total',
            field=models.IntegerField(default=False, null=True),
        ),
    ]
