# Generated by Django 3.0.7 on 2020-10-01 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0010_remove_order_town_or_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='town_or_city',
            field=models.CharField(default=0, max_length=40),
            preserve_default=False,
        ),
    ]
