# Generated by Django 3.0.7 on 2020-10-01 23:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0012_auto_20201001_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderlineitem',
            name='Movie',
            field=models.CharField(editable=False, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='orderlineitem',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='checkout.order'),
        ),
    ]
