# Generated by Django 3.0.7 on 2020-10-01 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0026_auto_20200810_0956'),
        ('checkout', '0013_auto_20201001_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderlineitem',
            name='Movie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.Movies'),
        ),
    ]
