# Generated by Django 3.0.7 on 2020-10-02 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0015_auto_20201001_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderlineitem',
            name='lineitem_total',
            field=models.IntegerField(null=True),
        ),
    ]
