# Generated by Django 3.0.7 on 2020-10-02 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0016_auto_20201001_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_cost',
            field=models.IntegerField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='grand_total',
            field=models.IntegerField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_total',
            field=models.IntegerField(default=False),
        ),
    ]
