# Generated by Django 3.0.7 on 2020-10-05 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0018_auto_20201004_0850'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='lineitem_total',
            field=models.IntegerField(null=True),
        ),
    ]
