# Generated by Django 3.0.7 on 2020-10-05 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0019_order_lineitem_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='lineitem_total',
        ),
    ]
