# Generated by Django 3.0.7 on 2020-10-05 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0022_auto_20201005_0929'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderlineitem',
            old_name='order',
            new_name='orders',
        ),
    ]
