# Generated by Django 3.0.7 on 2020-10-06 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0023_auto_20201005_1004'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderlineitem',
            old_name='orders',
            new_name='order',
        ),
    ]
