# Generated by Django 3.0.7 on 2020-08-04 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0023_movies'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='original_title',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='poster',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='video',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='movies',
            name='TheatreId',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
