# Generated by Django 3.0.7 on 2020-08-10 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0024_auto_20200804_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='price',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='movies',
            name='genreids',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
