# Generated by Django 3.0.7 on 2020-08-10 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0025_auto_20200810_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
    ]
